# potato-project/docker-compose.yml

name: basic_Potato

services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_Backbone
    hostname: rabbitmq  # Important for services to find it
    ports:
      - "5672:5672"  # Standard AMQP port
      - "15672:15672"  # Management port  (http://localhost:15672)
    environment:
      RMQ_DEFAULT_USER: "guest"
      RMQ_DEFAULT_PASS: "guest" # CHANGE THIS FOR PRODUCTION!
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persist data (queues, messages)

  ear:
    build:
      context: ./services
      dockerfile: ear/discordpy_chat/Dockerfile
    image: ear/discordpy-chat-ear
    container_name: ${COMPOSE_PROJECT_NAME}_Ear
    env_file:
      - ./services/ear/discordpy_chat/.env
      - .env
    depends_on:
      - rabbitmq

  brain:
    build:
      context: ./services
      dockerfile: brain/echo/Dockerfile
    image: brain/echo-brain
    container_name: ${COMPOSE_PROJECT_NAME}_Brain
    env_file:
      - .env
    depends_on:
      - rabbitmq

  mouth:
    build:
      context: ./services
      dockerfile: mouth/console_out/Dockerfile
    image: mouth/console-out-mouth
    container_name: ${COMPOSE_PROJECT_NAME}_Mouth
    env_file:
      - .env
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data:
